TabloidMVC/Models/Post.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace TabloidMVC.Models
{
    public class Post
    {
        public int Id { get; set; }

        [Required]
        public string Title { get; set; }

        [Required]
        public string Content { get; set; }

        [DisplayName("Header Image URL")]
        public string ImageLocation { get; set; }

        public DateTime CreateDateTime { get; set; }

        [DisplayName("Published")]
        [DataType(DataType.Date)]
        public DateTime? PublishDateTime { get; set; }

        public bool IsApproved { get; set; }

        [Required]
        [DisplayName("Category")]
        public int CategoryId { get; set; }
        public Category Category { get; set; }

        [DisplayName("Author")]
        public int UserProfileId { get; set; }
        public UserProfile UserProfile { get; set; }
    }
}

TabloidMVC/Models/ViewModels/CreatePostTagViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TabloidMVC.Models.ViewModels
{
    public class CreatePostTagViewModel
    {
        public List<Tag> TagList { get; set; }

        //********************add int labeled tag id ???
        public Post Post { get; set; }
        //allows user to view full list of tags when adding to single post
    }
}

TabloidMVC/Controllers/CommentController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using TabloidMVC.Models;
using TabloidMVC.Repositories;
using Microsoft.VisualBasic;
using TabloidMVC.Models.ViewModels;

namespace TabloidMVC.Controllers
{
    public class CommentController : Controller
    {

        private int GetCurrentUserProfileId()
        {
            string id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return int.Parse(id);
        }
        private readonly IPostRepository _postRepo;
        private readonly ICommentRepository _commentRepo;

        public CommentController(IPostRepository postRepository, ICommentRepository commentRepository)
        {
            _postRepo = postRepository;
            _commentRepo = commentRepository;
        }
        // GET: CommentController

        public ActionResult Index(int id)
        {
            CommentViewModel vm = new CommentViewModel()
            {
                CommentList = _commentRepo.GetAllCommentsByPostId(id),
                Posts = new Post()
                {
                    Id = id
                }

        };
            
            return View(vm);
        }

        // GET: CommentController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: CommentController/Create
        public ActionResult Create(int id)
        {
           Post posts = _postRepo.GetPublishedPostById(id);

            CommentViewModel vm = new CommentViewModel()
            {
                Comment = new Comment(),
                Posts = posts
            };                                                                             
            vm.Comment.PostId = id;

            return View(vm);
        }

        // POST: CommentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Comment Comment, Post Posts)
        {
            try
            {
                Comment.UserProfileId = GetCurrentUserProfileId();
                Comment.PostId = Posts.Id;

                _commentRepo.CreateComment(Comment);

                return RedirectToAction("Index", new {id=Comment.PostId});

        }
            catch
            {
                return View(Comment);
    }
}

        // GET: CommentController/Edit/5
        public ActionResult Edit(int id)
        {
            Comment Comment = _commentRepo.GetCommentById(id);
            CommentViewModel vm = new CommentViewModel()
            {
                Comment = Comment

            };

            return View(vm);
        }

        // POST: CommentController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Comment comment, Post Posts)
        {
            try
            {
             
            _commentRepo.UpdateComment(comment);
            return RedirectToAction("Index", new { id = comment.PostId });
        }
            catch
            {
                return View();
    }
}

        // GET: CommentController/Delete/5
        public ActionResult Delete(int id)
        {
           
            Comment Comment = _commentRepo.GetCommentById(id);

            CommentViewModel vm = new CommentViewModel()
            {
                Comment = Comment
              
            };
            
            return View(vm);
        }

        // POST: CommentController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Comment comment, Post Posts)
        {

            try
            {
                _commentRepo.DeleteComment(id);
                return RedirectToAction("Index", new { id = comment.PostId });
        }
            catch
            {
                return View();
    }
}
    }
}

TabloidMVC/Controllers/PostController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.VisualBasic;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using TabloidMVC.Models;
using TabloidMVC.Models.ViewModels;
using TabloidMVC.Repositories;

namespace TabloidMVC.Controllers
{
    [Authorize]
    public class PostController : Controller
    {
        private readonly IPostRepository _postRepository;
        private readonly ICategoryRepository _categoryRepository;
        private readonly ITagRepository _tagRepository;

        public PostController(IPostRepository postRepository, ICategoryRepository categoryRepository, ITagRepository tagRepository)
        {
            _postRepository = postRepository;
            _categoryRepository = categoryRepository;
            _tagRepository = tagRepository;
        }
        //^^ allows PostContoller to access the methods in the TagRepository

        public IActionResult Index()
        {
            var posts = _postRepository.GetAllPublishedPosts();
            return View(posts);
        }

        public IActionResult Details(int id)
        {
            var post = _postRepository.GetPublishedPostById(id);
            if (post == null)
            {
                int userId = GetCurrentUserProfileId();
                post = _postRepository.GetUserPostById(id, userId);
                if (post == null)
                {
                    return NotFound();
                }
            }
            return View(post);
        }

        public IActionResult Create()
        {
            var vm = new PostCreateViewModel();
            vm.CategoryOptions = _categoryRepository.GetAll();
            return View(vm);
        }

        [HttpPost]
        public IActionResult Create(PostCreateViewModel vm)
        {
            try
            {
                vm.Post.CreateDateTime = DateAndTime.Now;
                vm.Post.IsApproved = true;
                vm.Post.UserProfileId = GetCurrentUserProfileId();

                _postRepository.Add(vm.Post);

                return RedirectToAction("Details", new { id = vm.Post.Id });
            }
            catch
            {
                vm.CategoryOptions = _categoryRepository.GetAll();
                return View(vm);
            }
        }

        public ActionResult Delete(int id)
        {
            Post post = _postRepository.GetPublishedPostById(id);

            return View(post);
        }

        // POST: Post/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int Id, Post post)
        {
            try
            {
                _postRepository.DeletePost(Id);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(post);
            }
        }

        public ActionResult Edit(int id)
        {
            Post post = _postRepository.GetPublishedPostById(id);

            if (post == null)
            {
                return NotFound();
            }

            var vm = new PostCreateViewModel();
            vm.Post = post;
            vm.CategoryOptions = _categoryRepository.GetAll();
            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, PostCreateViewModel vm)
        {
            try
            {
                _postRepository.UpdatePost(vm.Post);

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View(vm.Post);
            }
        }

        public IActionResult MyPosts()
            {
                int CurrentUser = GetCurrentUserProfileId();
                List<Post> posts = _postRepository.GetUsersPosts(CurrentUser);
                return View(posts);
            }

        private int GetCurrentUserProfileId()
          {
            string id = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return int.Parse(id);
          }

        // GET: PostController/Create
        public ActionResult CreatePostTag(int id)
        {
            CreatePostTagViewModel ptvm = new CreatePostTagViewModel();

            ptvm.TagList = _tagRepository.GetAllTags();
            ptvm.Post = new Post();
            ptvm.Post.Id = id;

            return View(ptvm);
         
        }

        // POST: PostController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePostTag(int postId, int tagId)
        {
            try
            {
                _postRepository.AddTagToPost(postId, tagId);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
            
        }
    }

}

TabloidMVC/Views/Post/Create.cshtml
@model TabloidMVC.Models.ViewModels.PostCreateViewModel

@{
    ViewData["Title"] = "Create";
}



<div class="container pt-5">
    <div class="row justify-content-center">
        <div class="card col-md-12 col-lg-8">
            <h3 class="mt-3 text-primary text-center card-title">What do you have to say?</h3>
            <form class="mt-5 card-body" asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Post.Title" class="control-label"></label>
                    <input asp-for="Post.Title" class="form-control" />
                    <span asp-validation-for="Post.Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.ImageLocation" class="control-label"></label>
                    <input asp-for="Post.ImageLocation" class="form-control" />
                    <span asp-validation-for="Post.ImageLocation" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.PublishDateTime" class="control-label"></label>
                    <input asp-for="Post.PublishDateTime" class="form-control" />
                    <span asp-validation-for="Post.PublishDateTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.CategoryId" class="control-label"></label>
                    <select asp-for="Post.CategoryId" class="form-control">
                        @foreach (var category in Model.CategoryOptions)
                        {
                            <option value="@category.Id">@category.Name</option>
                        }
                    </select>
                    <span asp-validation-for="Post.CategoryId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Post.Content" class="control-label"></label>
                    <textarea asp-for="Post.Content" rows="15" class="form-control post__content-input"></textarea>
                    <span asp-validation-for="Post.Content" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="SAVE" class="btn btn-primary btn-block" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TabloidMVC/Views/Post/CreatePostTag.cshtml
@model TabloidMVC.Models.ViewModels.CreatePostTagViewModel;
@{
    ViewData["Title"] = "CreatePostTag";
}

<h1>CreatePostTag</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TagList[0].Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.TagList)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>

TabloidMVC/Views/Post/Delete.cshtml
@model TabloidMVC.Models.Post

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PublishDateTime)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PublishDateTime)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

TabloidMVC/Views/Post/Details.cshtml
@model TabloidMVC.Models.Post

@{
    ViewData["Title"] = $"Post - {Model.Title}";
}

<div class="container pt-5">
    <div class="post">
        <section class="px-3">
            <div class="row justify-content-between">
                <h1 class="text-secondary">@Model.Title</h1>
                <h1 class="text-black-50">@Model.Category.Name</h1>
            </div>
            <div class="row justify-content-between">
                <p class="text-secondary">Written by @Model.UserProfile.DisplayName</p>
                <p class="text-black-50">Published on @Html.DisplayFor(model => model.PublishDateTime)</p>
            </div>
            <div class="row">
                <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-outline-primary mx-1" title="Edit">
                    <i class="fas fa-pencil-alt"></i>
                </a>
                <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-outline-primary mx-1" title="Delete">
                    <i class="fas fa-trash"></i>
                </a>
                <a asp-controller="Comment" asp-action="Index" asp-route-id="@Model.Id" title="Comments">
                    <i class="fas fa-comments"></i>
                </a>
                <a asp-controller="Post" asp-action="CreatePostTag" asp-route-id="@Model.Id" title="Manage Tags">
                    @*asp-action navigates to the CreatePostTag method in the postController*@
                    <i class="fas fa-comments"></i>
                </a>
            </div>
        </section>
        <hr />
        @if (!string.IsNullOrWhiteSpace(Model.ImageLocation))
        {
            <section class="row justify-content-center">
                <div>
                    <img src="@Model.ImageLocation" />
                </div>
            </section>
        }
        <section class="row post__content">
            <p class="col-sm-12 mt-5">@Html.DisplayFor(model => model.Content)</p>
        </section>
    </div>
</div>

TabloidMVC/Views/Post/Edit.cshtml
@model TabloidMVC.Models.ViewModels.PostCreateViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="Post.Id" type="hidden" />
            </div>
            <div class="form-group">
                <label asp-for="Post.Title" class="control-label"></label>
                <input asp-for="Post.Title" class="form-control" />
                <span asp-validation-for="Post.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Post.Content" class="control-label"></label>
                <input asp-for="Post.Content" class="form-control" />
                <span asp-validation-for="Post.Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Post.ImageLocation" class="control-label"></label>
                <input asp-for="Post.ImageLocation" class="form-control" />
                <span asp-validation-for="Post.ImageLocation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Post.PublishDateTime" class="control-label"></label>
                <input asp-for="Post.PublishDateTime" class="form-control" />
                <span asp-validation-for="Post.PublishDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Post.CategoryId" class="control-label"></label>
                <select asp-for="Post.CategoryId" class="form-control">
                    @foreach (var category in Model.CategoryOptions)
                    {
                        <option value="@category.Id">@category.Name</option>
                    }
                </select>
                <span asp-validation-for="Post.CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TabloidMVC/Views/Post/Index.cshtml
@model IEnumerable<TabloidMVC.Models.Post>

@{
    ViewData["Title"] = "Index";
}


<div class="container pt-5">
    <h1>Posts</h1>

    <p>
        <a class="btn btn-primary" asp-action="Create">New Post</a>
    </p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Title)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UserProfileId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CategoryId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PublishDateTime)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Title)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UserProfile.DisplayName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PublishDateTime)
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-outline-primary mx-1" title="View">
                            <i class="fas fa-eye"></i>
                        </a>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-primary mx-1" title="Edit">
                            <i class="fas fa-pencil-alt"></i>
                        </a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-outline-primary mx-1" title="Delete">
                            <i class="fas fa-trash"></i>
                        </a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

TabloidMVC/Views/Post/MyPosts.cshtml
@model IEnumerable<TabloidMVC.Models.Post>

@{
    ViewData["Title"] = "MyPosts";
}

<h1>MyPosts</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>

            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Content)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImageLocation)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PublishDateTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Content)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImageLocation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PublishDateTime)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>